### ISSUE TITLE
TODO: Discord Events

### ISSUE THREAD

**Issue by The-CJ** [The-CJ/Phaazebot#107]
Join , Leave etc. messages

**Comment by The-CJ** [comment]
Seems like on_join and on_leave, already where therem but raised an error?

**Comment by The-CJ** [comment]
<pre>
[ERROR]: (Discord) Ignoring exception in on_member_remove
Traceback (most recent call last):
 File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 312, in _run_event
   await coro(*args, **kwargs)
 File "/root/Dev/Phaazebot/Platforms/Discord/main_discord.py", line 67, in on_member_remove
   self.BASE.PhaazeDB.updateQuery(
 File "/root/Dev/Phaazebot/Utils/Classes/dbconn.py", line 157, in updateQuery
   Cursor.execute(statement, values)
 File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 551, in execute
   self._handle_result(self._connection.cmd_query(stmt))
 File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 490, in cmd_query
   result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
 File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 395, in _handle_result
   raise errors.get_exception(packet)
mysql.connector.errors.DataError: 1292 (22007): Truncated incorrect DOUBLE value: ''
</pre>

**Comment by The-CJ** [comment]
Found it,
https://stackoverflow.com/questions/3456258/mysql-truncated-incorrect-double-value

Need to ensure types (str, int, etc...) in selects and stuff.
gonna make a new issue for this

**Comment by The-CJ** [comment]
#119 was the problem of this, but its fixed now
