### ISSUE TITLE
Twitch Alert Thread trowing error

### ISSUE THREAD

**Issue by The-CJ** [The-CJ/Phaazebot#65]
<pre>
Exception in thread T_Alerts:
Traceback (most recent call last):
File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "Phaaze_main.py", line 389, in run
self.loop.run_until_complete(BASE.modules._Twitch_.Alerts.Main.start())
File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
return future.result()
File "/root/Dev/Phaazebot/_TWITCH_/Alerts.py", line 67, in start
self.BASE.PhaazeDB.update(of="twitch/alerts", content=game_update)
File "/usr/lib/python3.6/site-packages/PhaazeDBC/__init__.py", line 108, in update
res = json.loads(r.text)
File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
return _default_decoder.decode(s)
File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
Expecting value: line 1 column 1 (char 0)
Error handling request
Traceback (most recent call last):
File "/usr/lib64/python3.6/site-packages/aiohttp/web_protocol.py", line 242, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
</pre>

**Comment by The-CJ** [comment]
Seems like a JSON decode error from DB. gonna fix on DB site
