### ISSUE TITLE
Catch erros in http requests

### ISSUE THREAD

**Issue by The-CJ** [The-CJ/Phaazebot#82]
<pre>
Error handling request
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 275, in data_received
   messages, upgraded, tail = self._request_parser.feed_data(data)
 File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
</pre> 
and 
<pre>
Task exception was never retrieved
future: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at /usr/local/lib/python3.6/dist-packages/websockets/protocol.py:428> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 434, in run
   msg = yield from self.read_message()
 File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 456, in read_message
   frame = yield from self.read_data_frame(max_size=self.max_size)
 File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 511, in read_data_frame
   frame = yield from self.read_frame(max_size)
 File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 546, in read_frame
   self.reader.readexactly, is_masked, max_size=max_size)
 File "/usr/local/lib/python3.6/dist-packages/websockets/framing.py", line 86, in read_frame
   data = yield from reader(2)
 File "/usr/lib/python3.6/asyncio/streams.py", line 674, in readexactly
   yield from self._wait_for_data('readexactly')
 File "/usr/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
   yield from self._waiter
 File "/usr/lib/python3.6/asyncio/selector_events.py", line 725, in _read_ready
   data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
</pre>

**Comment by The-CJ** [comment]
soo apparently that is fixed by a new aiohttp version, i will still watch this doh

**Comment by The-CJ** [comment]
Seems like the error still exists.

<pre>
Error handling request
Traceback (most recent call last):
 File "/usr/local/lib/python3.8/dist-packages/aiohttp/http_parser.py", line 445, in parse_message
   raise BadStatusLine(version)
aiohttp.http_exceptions.BadStatusLine: RTSP/1.0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_protocol.py", line 275, in data_received
   messages, upgraded, tail = self._request_parser.feed_data(data)
 File "/usr/local/lib/python3.8/dist-packages/aiohttp/http_parser.py", line 264, in feed_data
   msg = self.parse_message(self._lines)
 File "/usr/local/lib/python3.8/dist-packages/aiohttp/http_parser.py", line 447, in parse_message
   raise BadStatusLine(version)
aiohttp.http_exceptions.BadStatusLine: RTSP/1.0</pre>

**Comment by The-CJ** [comment]
No http errors shown up since about 5 weeks...
if there will be no more for another month i gonna close this error
